### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by astroboyReloaded** [jlvFlores/Portfolio-setup-and-mobile-first#8]
- It would be better if you change the name at the left upper corner and raplece it with your name, it makes more sense and will the people know that it's your portfolio
- You did an awasome job with the animations and transitions but it could be even better if you add some transition time to hover effects like the buttons and li tags I think 0.4s could be a good transition time, it would make your portfolio more dynamic
- Your README is professional
- Maybe you could add server as GitHub Pages
- It be nice if the clickable elements had a cursor: pointer when hovered
- You could add margin to the buttons so they don't change size when hovered
- Organized CSS
- I think your .tags column-gap is making them push the size of the screen out of the body, maybe making it a relative unit would help.

**Comment by jlvFlores** [comment]
Thanks, I just submitted the changes to my repository.
